version: '3'

services:
  test-app:
    container_name: app-con
    build:
      context: ./dockerfiles/development/java-app
      args:
        UID: 1000
        GID: 1000 
    expose: 
      - 8080
      - 80
    ports:
      - 8080:8080
      - 80:80
    networks:
      - test-network
    volumes:
      - ./:/home/node/app:rw # project
      - /home/vs/.vscode/extensions:/home/node/.vscode-server/extensions # for vscode
      - /etc/timezone:/etc/timezone:ro # timezone
      - /etc/localtime:/etc/localtime:ro # localtime
    # restart: unless-stopped
          
  test-db:
    container_name: db-con
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # start sql scripts
      - /etc/timezone:/etc/timezone:ro # timezone
      - /etc/localtime:/etc/localtime:ro # localtime
    ports:
      - "5432:5432" #debug
    networks:
      - test-network
    # restart: unless-stopped

networks:
  test-network:
    driver: bridge

